training:
  epochs: 150
  batch_size: 64
  validation_split: 0.2
  early_stopping_patience: 15

features:
  input_columns: ["attempts", "time_spent", "accuracy", "efficiency"]
  target_column: "difficulty"
  synthetic_samples: 10000
